
var libList = function() {

	var item = function(verPaths, cdnjsName) {
		if ( ! (verPaths instanceof Array)) {
            verPaths = [ verPaths ];
        }
        this.verPaths  = verPaths;
        this.cdnjsName = cdnjsName || '';
	};
	
	this.list = {
		'Ace'                        : new item('ace', 'ace'),
        'ActiveJS'                   : new item('ActiveSupport'),
        'AngularJS'                  : new item('angular.version.full'),
        'Backbone.js'                : new item('Backbone.VERSION', 'backbone.js'),
        'Backbone localStorage'      : new item('Store', 'backbone-localstorage.js'),
        'Base2'                      : new item('base2.version'),
        'Batman.js'                  : new item('Batman'),
        'CamanJS'                    : new item('Caman.version.release', 'camanjs'),
        'Chainvas'                   : new item('Chainvas'),
        'CoffeeScript'               : new item('CoffeeScript', 'coffee-script'),
        'Clientcide Libraries'       : new item('Clientcide.version'),
        'Crafty'                     : new item('Crafty.init'),
        'CSS 3 Finalize'             : new item('$.cssFinalize', 'css3finalize'),
        'CSS 3 Pie'                  : new item('PIE', 'css3pie'),
        'Cufón'                      : new item('Cufon', 'cufon'),
        'D3'                         : new item('d3.version', 'd3'),
        'Datejs'                     : new item('Date.today', 'datejs'),
        'Davis.js'                   : new item('Davis.version', 'davis.js'),
        'DD_belatedPNG'              : new item('DD_belatedPNG', 'dd_belatedpng'),
        'DocumentUp'                 : new item('DocumentUp', 'documentup'),
        'DHTMLX'                     : new item('dhtmlx'),
        'Dojo'                       : new item('dojo.version', 'dojo'),
        'Dojo Mobile'                : new item('dojox.mobile'),
        'Ember'                      : new item('Ember.VERSION', 'ember.js'),
        'Enyo'                       : new item('enyo'),
        'Ext JS'                     : new item(['Ext.version','Ext.versions.core.version'], 'ext-core'),
        'fancyBox'                   : new item('$.fancybox.version', 'fancybox'),
        'flexie'                     : new item('Flexie.version', 'flexie'),
        'Flot'                       : new item('$.plot.version', 'flot'),
        'Galleria'                   : new item('Galleria.version', 'galleria'),
        'Google Chrome Frame'        : new item('CFInstall', 'chrome-frame'),
        'g.Raphaël'                  : new item('Raphael.fn.g', 'graphael'),
        'Glow'                       : new item('glow.VERSION'),
        'Handlebars'                 : new item('Handlebars.VERSION', 'handlebars.js'),
        'Head JS'                    : new item('head.js', 'headjs'),
        'Highcharts JS'              : new item('Highcharts.version', 'highcharts'),
        'History.js'                 : new item('History.Adapter', 'History.js'),
        'Hogan.js'                   : new item('Hogan'),
        'html5shiv'                  : new item('html5', 'html5shiv'),
        'ICanHaz.js'                 : new item('ich.VERSION', 'ICanHaz.js'),
        'JS State Machine'           : new item('StateMachine.VERSION', 'javascript-state-machine'),
        'JavaScriptMVC'              : new item('steal.fn'),
        'jQuery'                     : new item('jQuery.fn.jquery', 'jquery'),
        'jQuery Mobile'              : new item('jQuery.mobile'),
        'jQuery throttle / debounce' : new item('jQuery.debounce', 'jquery-throttle-debounce'),
        'jQuery Tools'               : new item('jQuery.tools.version', 'jquery-tools'),
        'jQuery Cycle'               : new item('jQuery.fn.cycle.ver', 'jquery.cycle'),
        'jQuery UI'                  : new item('$.ui.version', 'jqueryui'),
        'js-signals'                 : new item('signals.VERSION', 'js-signals'),
        'JSXGraph'                   : new item('JXG', 'jsxgraph'),
        'Kendo UI'                   : new item('kendo'),
        'Knockout'                   : new item('ko', 'knockout'),
        'LABjs'                      : new item('$LAB', 'labjs'),
        'LESS'                       : new item('less', 'less.js'),
        'LightningJS'                : new item('lightningjs'),
        'LungoJS'                    : new item('LUNGO.VERSION'),
        'Masonry'                    : new item('jQuery.fn.masonry', 'masonry'),
        'Midori'                     : new item('midori.domReady'),
        'Modernizr'                  : new item('Modernizr._version', 'modernizr'),
        'MochiKit'                   : new item('MochiKit.MochiKit.VERSION'),
        'MooTools A.R.T.'            : new item('ART.version'),
        'MooTools Core'              : new item('MooTools.version', 'mootools'),
        'MooTools More'              : new item('MooTools.More.version'),
        'Mustache'                   : new item('Mustache.version', 'mustache.js'),
        'Ninja UI'                   : new item('jQuery.ninja.version', 'ninjaui'),
        'Noisy'                      : new item('jQuery.fn.noisy', 'noisy'),
        'oCanvas'                    : new item('oCanvas', 'ocanvas'),
        'o2.js'                      : new item('o2.version'),
        'PageDown'                   : new item('Markdown', 'pagedown'),
        'Prettify'                   : new item('prettyPrint', 'prettify'),
        'Processing.js'              : new item('Processing.version', 'processing.js'),
        'Prototype'                  : new item('Prototype.Version', 'prototype'),
        'PubNub'                     : new item('PUBNUB', 'pubnub'),
        'Qooxdoo'                    : new item('qx.$$libraries.qx.version'),
        'Raphaël'                    : new item('Raphael.version', 'raphael'),
        'Rico'                       : new item('Rico.Version'),
        'RightJS'                    : new item('RightJS.version'),
        'Sammy'                      : new item('Sammy.VERSION', 'sammy.js'),
        '$script.js'                 : new item('$script', 'script.js'),
        'Script.aculo.us'            : new item('Scriptaculous.Version', 'scriptaculous'),
        'Scripty2'                   : new item('S2.Version'),
        'Sencha Touch'               : new item('Ext.util.TapRepeater'),
        'Sizzle'                     : new item('Sizzle', 'sizzle'),
        'Snack'                      : new item('snack.v'),
        'Socket.io'                  : new item('io.version', 'socket.io'),
        'Spine'                      : new item('Spine.version', 'spinejs'),
        'SproutCore'                 : new item('SC.isReady'),
        'Spry'                       : new item('Spry.$'),
        'Sugar'                      : new item('Object.SugarMethods'),
        'SWFObject'                  : new item('swfobject', 'swfobject'),
        'Terrific'                   : new item('Tc'),
        'Tiny Scrollbar'             : new item('jQuery.fn.tinyscrollbar', 'tinyscrollbar'),
        'Twitter Lib'                : new item('twitterlib', 'twitterlib.js'),
        'Underscore.js'              : new item('_.VERSION', 'underscore.js'),
        'Waypoints'                  : new item('jQuery.waypoints', 'waypoints'),
        'Wink toolkit'               : new item('wink'),
        'WebFont Loader'             : new item('WebFont', 'webfont'),
        'xui'                        : new item('x$', 'xuijs'),
        'yepnope.js'                 : new item('yepnope', 'yepnope'),
        'YUI'                        : new item(['YAHOO.VERSION', 'YUI.version'], 'yui'),
        'Zepto'                      : new item('Zepto', 'zepto'),
        'ZK'                         : new item('zk.version')
	};

};

module.exports = new libList();